FROM debian:bookworm-slim

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    build-essential \
    pkg-config \
    libssl-dev \
    libffi-dev \
    python3-dev \
    # php \
    virtualenv \
    python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    
WORKDIR /project/

COPY . /TeleDocker/